config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register' }
  require 'sidekiq/web'
  
  resources :occurrences, only: [:index, :show]
  resources :users

  #Set default routes
  root to: 'occurrences#index'
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/occurrence.rb
class Occurrence < ActiveRecord::Base
  belongs_to :twitter_user

  validates_presence_of :tweet_id, :content, :tweet_created_at
end

app/models/twitter_user.rb
class TwitterUser < ActiveRecord::Base
	has_many :occurrences, dependent: :destroy

	validates_presence_of :name, :screen_name, :twitter_id


	#This method of create ou update twitter user
	def self.create_or_update_twitter_user(user)
		
		TwitterUser.where(twitter_id: user[:id_str]).first_or_initialize do |twitter_user|
			twitter_user.name = user[:name]
			twitter_user.screen_name = "@#{user[:screen_name]}"
			twitter_user.followers = user[:followers_count]

			twitter_user.save!
		end

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

	validates_presence_of :name 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  before_action :set_occurence, only: [:show]
  before_action :authenticate_user!

  def index
  	@occurrences = Occurrence.group(:twitter_user_id, :id).sort_by {|o| o.twitter_user.followers}.reverse.paginate(:page => params[:page], :per_page => 30)
  end

  def show
  end

  def set_occurence
  	@occurrence = Occurrence.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show, :destroy]
  before_action :authenticate_user!
  
  def index
  	@users = User.all
  end

  def show
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:notice] = "Usuário criado com sucesso."
  		redirect_to @user
  	else
  		render :new
  	end
  end

  def edit
  end

  def update
  	if @user.update(user_params)
  		flash[:notice] = "Usuário alterado com sucesso."
  		redirect_to @user
  	else
  		render :edit
  	end
  end

  def destroy
    if @user.destroy
      flash[:notice] = "O usuário foi removido com sucesso."
      redirect_to users_url
    end
  end

  private
  def set_user
  	@user = User.find(params[:id])
  end

  def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def l(timestamp, format=nil)
		timestamp.to_formatted_s(format.nil? ? :default : format.to_sym)
	end
end

app/helpers/occurrences_helper.rb
module OccurrencesHelper
	def twitter_link(username)
		url = "https://twitter.com/" + username(username)
	end

	def tweet_link(username, tweet_id)
		url = "https://twitter.com/#{username(username)}/status/#{tweet_id}"
	end

	def username(username)
		username.gsub('@', '').strip
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>DevtestLocaweb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      	DevTest
      <% end -%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? -%>
        <ul class="nav navbar-nav">
          <li><%= link_to "Ocorrências", occurrences_url %></li>
          <li><%= link_to "Usuários", users_url %></li>
        </ul>
      <% end -%>

      <ul class="nav navbar-nav pull-right">
        <li>          
          <div id="user_nav">
            <% if user_signed_in? %>
              Logado como <%= current_user.email %> - <%= current_user.name %>
              <%= link_to "Sair", destroy_user_session_url, :method => :delete , class: 'btn btn-danger navbar-btn' %>
            <% else %>
              <%= link_to "Entrar", new_user_session_url, class: 'btn btn-default navbar-btn' %>
            <% end %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <% flash.each do |key, msg| -%>
    <p class="<%= key %>"> <%= msg %> </p>
  <% end -%>
  
  <%= yield %>
</div>

</body>
</html>

app/views/occurrences/index.html.erb
<h1>Ocorrências</h1>

<% if @occurrences.size == 0 %>
	<h3> Não dados para serem mostrados </h3>
<% else %>

	<table class="table table-strip">
		<thead>
			<tr>
				<th>Usuário</th>
				<th>Seguidores</th>
				<th>Mensagem</th>
				<th>Horário</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @occurrences.each do |occurrence| %>
				<tr>
					<td title="<%= occurrence.twitter_user.name %>"><%= link_to occurrence.twitter_user.screen_name , twitter_link(occurrence.twitter_user.screen_name), target: '_blank' %></td>
					<td><%= occurrence.twitter_user.followers %></td>
					<td><%= occurrence.content %></td>
					<td><%= link_to l(occurrence.tweet_created_at, :long), tweet_link(occurrence.twitter_user.screen_name, occurrence.tweet_id), target: '_blank' %></td>
					<td><%= link_to "Detalhes", occurrence %></td>
				</tr>
			<% end -%>
		</tbody>
	</table>

	<%= will_paginate @occurrences %>

<% end %>

app/views/occurrences/show.html.erb
<h1>Detalhes</h1>
<p>
	<table>
		<tbody>
			<tr>
				<td>Nome:</td>
				<td><%= @occurrence.twitter_user.name %></td>
			</tr>
			<tr>
				<td>Apelido:</td>
				<td><%= @occurrence.twitter_user.screen_name %></td>
			</tr>
			<tr>
				<td>Seguidores:</td>
				<td><%= @occurrence.twitter_user.followers %></td>
			</tr>
			<tr>
				<td>Menssagem:</td>
				<td><%= @occurrence.content %></td>
			</tr>
			<tr>
				<td>Favoritos</td>
				<td><%= @occurrence.favourites_count %></td>
			</tr>
			<tr>
				<td>Postado em</td>
				<td><%= l(@occurrence.tweet_created_at, :long) %></td>
			</tr>
		</tbody>
	</table>
</p>

app/views/users/_form.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-9">
			<%= simple_form_for @user , html: {class: 'form-horizontal'} do |f| %>
				<div class="form-group">
					<%= f.input :name %>
				</div>
				<div class="form-group">
					<%= f.input :email %>
				</div>
				<div class="form-group">
					<%= f.input :password %>
				</div>
				<div class="form-group">
					<%= f.input :password_confirmation %>
				</div>

				<div class="form-actions">
					<%= f.button :submit , class: 'btn btn-success' %>
				</div>
			<% end -%>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<h1>Editar usuário</h1>


<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-lg-9">
		<h1>Usuários</h1>
	</div>
	<div class="col-lg-3 poll-right">
		<%= link_to new_user_url, class: 'btn btn-primary' do %>
			Novo usuário
		<% end -%>
	</div>
</div>


<table class="table table-striped">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Email</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| -%>
			<tr>
				<td><%= user.name %></td>
				<td><%= user.email %></td>
				<td><%= link_to "Detalhes", user %></td>
				<td><%= link_to "Editar", edit_user_url(user) %></td>
				<td><%= link_to "Deletar", user, method: :delete %></td>
			</tr>
		<% end -%>
	</tbody>
</table>

app/views/users/new.html.erb
<h1>Novo usuário</h1>


<%= render 'form' %>

app/views/users/show.html.erb
<h1>Detalhes</h1>

<div class="col-lg-6">
	<table class="table table-striped">
		<tbody>
			<tr>
				<th>Nome</th>
				<td><%= @user.name %></td>
			<tr>
			<tr>
				<th>Email</th>
				<td><%= @user.email %></td>
			</tr>
			<tr>
				<th>Criado em</th>
				<td><%= l @user.created_at, :long %></td>
			</tr>
		</tbody>
	</table>
</div>